{{#very_good_analysis}}
include: package:very_good_analysis/analysis_options.yaml
{{/very_good_analysis}}
{{^very_good_analysis}}
include: package:flutter_lints/flutter.yaml
{{/very_good_analysis}}

analyzer:
  plugins:
    - custom_lint

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    avoid_print: warning

  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/l10n/**
    # Want to include generated files into your analysis? remove the following:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.g.dart

linter:
  rules:
    # TODO: customize the following based on your taste
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    always_use_package_imports: false
    one_member_abstracts: false

    prefer_relative_imports: true
    avoid_relative_lib_imports: true
